spring:
  application:
    name: letsgo-springboot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
   # url: jdbc:mariadb://43.203.228.33:3306/mydb
    url: jdbc:mariadb://127.0.0.1:3306/mydb
    username: mydbid
    password: mydbpw

mybatis:
  mapper-locations: classpath:mappers/placeMapper.xml
server:
  port: 5531