spring:
  application:
    name: letsgo-springboot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/mydb
    username: mydbid
    password: mydbpw
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    cache: false
    check-template-location: true

mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  port: 5531